export const STANDARD_MIN_CLASSIFIABLE_CHROMA = 0.03;
export const STANDARD_MIN_CLASSIFIABLE_CONFIDENCE = 0.35;

export const CLOSEUP_MIN_CLASSIFIABLE_CHROMA = 0.012;
export const CLOSEUP_MIN_CLASSIFIABLE_CONFIDENCE = 0.12;

export const DARK_PIXEL_LUMINANCE = 40;
export const BRIGHT_PIXEL_LUMINANCE = 215;
export const MIN_MEAN_LUMINANCE = 42;
export const MAX_MEAN_LUMINANCE = 220;
export const MAX_DARK_RATIO = 0.52;
export const MAX_BRIGHT_RATIO = 0.45;
export const MAX_STD_DEV = 70;
export const MIN_LIGHTING_SAMPLE_COUNT = 50;
export const HIGH_CONTRAST_RATIO_THRESHOLD = 0.18;
