// SYNC: Must match the runtime generated by virtualModuleSource() in vite.package-bindings.ts
declare module 'virtual:package-bindings' {
	type AssetPrimary = 'self' | 'cdn';
	type AssetKind = 'file' | 'dir';
	type AssetSource = 'primary' | 'fallback';

	export interface PackageAsset {
		readonly package: string;
		readonly version: string;
		readonly path: string;
		readonly kind: AssetKind;
		readonly localPath: string;
		readonly localUrl: string;
		readonly cdnUrl: string;
		readonly primary: AssetPrimary;
		readonly primaryUrl: string;
		readonly fallbackUrl: string;
	}

	export interface PackageAssetBinding {
		readonly package: string;
		readonly asset: (assetPath: string) => PackageAsset;
		readonly url: (assetPath: string, source?: AssetSource) => string;
	}

	export interface DownloadAsset {
		readonly id: string;
		readonly path: string;
		readonly localAvailable: boolean;
		readonly localUrl: string | null;
		readonly remoteUrl: string;
	}

	export const packageBindingsManifest: readonly PackageAsset[];
	export const packageDownloadsManifest: readonly DownloadAsset[];

	export function getPackageAsset(packageName: string, assetPath: string): PackageAsset;
	export function getDownloadAsset(assetPath: string): DownloadAsset;
	export function getDownloadBinding(downloadId: string): DownloadAsset;
	export function getPackageBinding(packageName: string): PackageAssetBinding;
}
