/**
 * @module
 * Type declarations for the `virtual:package-bindings` virtual module
 * generated at build time by `vite.package-bindings.ts`.
 *
 * SYNC: Must match the runtime generated by `generateVirtualModule()` in
 * `vite.package-bindings.ts`. No automated verification — enforced by
 * `SYNC:` comments only.
 */

declare module 'virtual:package-bindings' {
	/** Whether the self-hosted copy or CDN URL is the primary source. */
	type AssetPrimary = 'self' | 'cdn';

	/** Whether the asset config pointed to a single file or a directory. */
	type AssetKind = 'file' | 'dir';

	/** Selects which URL to return from {@link PackageAssetBinding.url}. */
	type AssetSource = 'primary' | 'fallback';

	/**
	 * A resolved package asset entry with both self-hosted and CDN URLs
	 * computed at build time.
	 */
	export interface PackageAsset {
		/** npm package name */
		readonly package: string;
		/** Installed semver version */
		readonly version: string;
		/** Asset path within the package */
		readonly path: string;
		/** Whether the original config pointed to a file or directory */
		readonly kind: AssetKind;
		/** Bundle-relative mount path (without base URL prefix) */
		readonly localPath: string;
		/** Fully resolved self-hosted URL (with base URL prefix) */
		readonly localUrl: string;
		/** Full jsdelivr CDN URL */
		readonly cdnUrl: string;
		/** Which source was configured as primary */
		readonly primary: AssetPrimary;
		/** URL from the primary source (self-hosted or CDN based on config) */
		readonly primaryUrl: string;
		/** URL from the fallback source (opposite of primary) */
		readonly fallbackUrl: string;
	}

	/**
	 * Scoped accessor for a single package's assets. Returned by
	 * {@link getPackageBinding}.
	 */
	export interface PackageAssetBinding {
		/** npm package name this binding is scoped to */
		readonly package: string;
		/**
		 * Looks up a specific asset within this package.
		 * @param assetPath - Path within the package
		 */
		readonly asset: (assetPath: string) => PackageAsset;
		/**
		 * Returns the URL for an asset, choosing primary or fallback.
		 * @param assetPath - Path within the package
		 * @param source - Which URL to return (default: `'primary'`)
		 */
		readonly url: (assetPath: string, source?: AssetSource) => string;
	}

	/**
	 * A resolved download asset entry (e.g. ML model) with local
	 * availability tracked at build time.
	 */
	export interface DownloadAsset {
		/** Stable binding identifier matching {@link DownloadConfig.id} */
		readonly id: string;
		/** Bundle-relative output path */
		readonly path: string;
		/** Whether the file was successfully downloaded and cached locally at build time */
		readonly localAvailable: boolean;
		/** Self-hosted URL if locally available, `null` otherwise */
		readonly localUrl: string | null;
		/** Original remote URL for direct fetching */
		readonly remoteUrl: string;
	}

	/** Full manifest of all resolved package assets. */
	export const packageBindingsManifest: readonly PackageAsset[];

	/** Full manifest of all resolved download assets. */
	export const packageDownloadsManifest: readonly DownloadAsset[];

	/**
	 * Looks up a package asset by package name and path.
	 *
	 * @param packageName - npm package name
	 * @param assetPath - Path within the package
	 * @returns Resolved asset entry
	 * @throws If the package/path combination is not registered
	 */
	export function getPackageAsset(packageName: string, assetPath: string): PackageAsset;

	/**
	 * Looks up a download asset by its bundle output path.
	 *
	 * @param assetPath - Bundle-relative path
	 * @returns Resolved download entry
	 * @throws If no download matches the path
	 */
	export function getDownloadAsset(assetPath: string): DownloadAsset;

	/**
	 * Looks up a download asset by its stable id.
	 *
	 * @param downloadId - Download identifier (e.g. `"face-landmarker-model"`)
	 * @returns Resolved download entry
	 * @throws If no download matches the id
	 */
	export function getDownloadBinding(downloadId: string): DownloadAsset;

	/**
	 * Returns a scoped accessor for all assets from a given package.
	 *
	 * @param packageName - npm package name
	 * @returns Binding with `asset()` and `url()` methods
	 * @throws If the package is not registered
	 */
	export function getPackageBinding(packageName: string): PackageAssetBinding;
}
